### ISSUE TITLE
Deserializing attachment.List() fails (expects array, instead object returned)

### ISSUE THREAD

**Issue by bluewalk** [bunq/sdk_csharp#140]
## Steps to reproduce:
1. Query attachments, eg NoteAttachmentMasterCardAction

## What should happen:
1. Deserialize Attachment property to an AttachmentMonetaryAccountPayment as the swagger info states at e.g. https://doc.bunq.com/#/note-attachment/List_all_NoteAttachment_for_User_MonetaryAccount_RequestInquiryBatch

## What happens:
1. Throws exception like 
```
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[Bunq.Sdk.Model.Generated.Object.AttachmentMonetaryAccountPayment]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
```

## Traceback
[//]: # (If there is a traceback please share it in a quote! You can do this by pasting the traceback text, highlighting it and pressing the quote button.)

> Path 'attachment.id', line 25, position 9.
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
>    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
>    at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
>    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
>    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
>    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
>    at Bunq.Sdk.Json.BunqJsonConvert.DeserializeObject[T](String value) in C:\Temp\Projects\sdk_csharp\BunqSdk\Json\BunqJsonConvert.cs:line 51
>    at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
>    at System.Linq.Enumerable.SelectIListIterator`2.ToList()
>    at Bunq.Sdk.Model.Core.BunqModel.FromJsonList[T](BunqResponseRaw responseRaw, String wrapper) in C:\Temp\Projects\sdk_csharp\BunqSdk\Model\Core\BunqModel.cs:line 110
>    at Bunq.Sdk.Model.Generated.Endpoint.NoteAttachmentMasterCardAction.List(Int32 mastercardActionId, Nullable`1 monetaryAccountId, IDictionary`2 urlParams, IDictionary`2 customHeaders) in C:\Temp\Projects\sdk_csharp\BunqSdk\Model\Generated\Endpoint\NoteAttachmentMasterCardAction.cs:line 173

## SDK version and environment
- Tested on [1.13.0](https://github.com/bunq/sdk_csharp/tree/1.13.0)
- [ ] Sandbox
- [x] Production

## Extra info:
[//]: # (Please provide any other relevant information here)
`NoteAttachmentMasterCardAction.cs` and others define the `attachment` property as 
```csharp
        public List<AttachmentMonetaryAccountPayment> Attachment { get; set; }
```

In fact the json returns an object. Changing these properties to a simle 
```csharp
        public AttachmentMonetaryAccountPayment Attachment { get; set; }
```
fixes the issue.

This applies too all NoteAttachmentXXX classes.

**Comment by bluewalk** [comment]
Is there a way we can also generate the "Generated" models?

**Comment by bluewalk** [comment]
Unfortunately v1.14.0 doesn't fix this...

**Comment by bluewalk** [comment]
Unfortunately also not fixed in v1.14.1

**Comment by bluewalk** [comment]
@angelomelonas Unfortunately still not resolved in v1.14.18

**Comment by bluewalk** [comment]
When will this issue be resolved?

**Comment by two-trick-pony-NL** [comment]
Hi! We're closing this issue as it's tied to an older version of our SDKs, and we've since completely revamped them as part of bunq Update 28.

This is a fresh start—we've tested the new SDKs extensively, and we’ll be putting them to the test again during our upcoming hackathon this Friday, where we’ll fix idiosyncrasies on the spot. (You’re welcome to [join us](https://www.bunq.com/en-nl/hackathon)!)

If this issue (or a new one) shows up with the updated SDKs, feel free to reopen or file a new report—we're happy to jump on it.
